-- https://github.com/CKolkey/config/blob/master/nvim/lua/config/ui/icons.lua
return {
  fillchars   = {
    foldopen  = "",
    foldclose = "",
    fold      = " ",
    foldsep   = " ",
    diff      = "╱",
    eob       = " ",
  },
  listchars   = {
    space    = " ",
    tab      = " ",
    trail    = "•",
    extends  = "❯",
    precedes = "❮",
    nbsp     = "␣",
  },
  diagnostics = {
    ERROR   = " ",
    WARNING = " ",
    INFO    = " ",
    HINT    = " ",
    DEBUG   = " ",
    TRACE   = " ",
  },
  dap         = {
    breakpoint           = " ",
    breakpoint_condition = " ",
    log_point            = " ",
    stopped              = " ",
    breakpoint_rejected  = " ",
    pause                = " ",
    play                 = " ",
    step_into            = " ",
    step_over            = " ",
    step_out             = " ",
    step_back            = " ",
    run_last             = " ",
    terminate            = " ",
  },
  git         = {
    status_added    = " ",
    status_removed  = " ",
    status_modified = " ",
    added           = " ",
    deleted         = " ",
    modified        = " ",
    renamed         = " ",
    untracked       = " ",
    ignored         = " ",
    unstaged        = " ",
    staged          = " ",
    conflict        = " ",
  },
  misc        = {
    collapsed     = " ",
    expanded      = " ",
    current       = " ",
    folder_empty  = "",
    folder_closed = "",
    folder_open   = "",
    file          = "",
  },
}
