setlocal colorcolumn=120
setlocal iskeyword+=:,#
setlocal tags+=$DATA_PATH/tags
setlocal autoindent
setlocal conceallevel=0
setlocal expandtab
setlocal foldmethod=syntax
setlocal formatoptions=tcq2l
setlocal shiftwidth=2
setlocal softtabstop=2
setlocal tabstop=4
